name: A workflow for my Hello World file
on: 
  repository_dispatch:
    types: launch
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: env
      - run: echo ${{ github.event.client_payload.myName }}
