# @format

name: A workflow for my Hello World file
on:
  repository_dispatch:
    types: launch
jobs:
  prep:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - run: curl -XGET 'http://3a3776fcc9d7.ngrok.io/admin/hotels'
      - run: env
  build:
    needs: prep
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hotelInfo: ${{fromJSON(needs.prep.outputs.HOTELS)}}
    steps:
      - run: echo ${{ matrix.hotelInfo }}
