# @format

name: A workflow for my Hello World file
on:
  repository_dispatch:
    types: launch
jobs:
  prep:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - name: Set variable
        id: some_id
        run: echo "::set-output name=action_fruit::strawberry"

        #- run: curl -s -XGET 'http://3a3776fcc9d7.ngrok.io/admin/hotels' > /tmp/hotels.json && echo "::set-output name=HOTELS::{\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}";
        #- run: sed -i 's/"/\\"/g' /tmp/hotels.json
        #- run: cat /tmp/hotels.json
  build:
    needs: prep
    runs-on: ubuntu-latest
    env:
      TESTING: ${{ needs.prep.outputs.some_id }}
    #strategy:
    #  matrix:
    #    hotelInfo: ${{fromJSON(needs.prep.outputs.HOTELS)}}
    steps:
      - run: echo "$TESTING"
      - run: env
