# @format

name: A workflow for my Hello World file
on:
  repository_dispatch:
    types: launch
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - run: HOTELS=$(curl -XGET 'http://3a3776fcc9d7.ngrok.io/admin/hotels') && echo "::set-env name=HOTELS::$HOTELS"
      - uses: actions/checkout@v1
      - run: env
      - run: echo ${{ github.event.client_payload.myName }}
    strategy:
      matrix:
        hotelInfo: ${{fromJSON(${{env.HOTELS}})}}
    steps:
      - run: echo ${{ matrix.hotelInfo }}
    
