name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: Set stage
        id: stage
        run: |
          echo "stage=staging";
          echo "tag=$(git describe --tags --abbrev=0)";
          echo "I'm here";
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump success context
        run: echo ${{success()}}
      - name: Dump failure context
        run: echo ${{failure()}}
      - name: Dump cancelled context
        run: echo ${{cancelled()}}

